### ISSUE TITLE
/var/lib/dpkg gone on image

### ISSUE THREAD

**Issue by sopsmattw** [lixmk/Wiegotcha#6]
/var/lib/dpkg folder is gone on the image. It causes issues when you try to reinstall packages or even  just run apt-get update. Did I miss a line in the instructions?

**Comment by lixmk** [comment]
Pretty sure I know what happened there. I needed to update the .img to use the latest version of Wiegotcha anyways so I'll fix that then. I'll close this once that is uploaded and the links in README.md fixed. As a temp work around, you can install manually using install.sh. It shouldn't have that problem.

**Comment by lixmk** [comment]
Finally got around to building a new .img with the latest version. It should also fix the problems you were having. Closing this issue out, but if for some reason it's still broken on your end, or you run into anything else, let me know.
